theme = "gruvbox"

[editor]
true-color = true
color-modes = true
middle-click-paste = false
cursorline = true
auto-format = true
rulers = [80]

[editor.cursor-shape]
insert = "bar"
select = "underline"
